### ISSUE TITLE
ValueError: Expected input batch_size to match target batch_size

### ISSUE THREAD

**Issue by ymym3412** [ujiuji1259/shinra-attribute-extraction#1]
READMEを参考にして以下のコマンドでコードを実行したところ次のようなエラーに遭遇しました。

```sh
python train.py \
    --input_path JP-5/data1/ujiie/shinra/tohoku_bert/JP-5/City \
    --model_path model \
    --lr 1e-5 \
    --bsz 32 \
    --epoch 50 \
    --grad_acc 1 \
    --grad_clip 1.0 
```

[エラー内容]
```
Traceback (most recent call last):
  File "train.py", line 151, in <module>
    train(model, train_dataset, valid_dataset, dataset[0].attributes, args)
  File "train.py", line 96, in train
    outputs = model(
  File "/my/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/my/workspace/shinra-attribute-extraction/src/model.py", line 89, in forward
    loss += loss_fct(logit.view(-1, 3), label.view(-1)) / len(labels)
  File "/my/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/my/venv/lib/python3.8/site-packages/torch/nn/modules/loss.py", line 1047, in forward
    return F.cross_entropy(input, target, weight=self.weight,
  File "/my/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2693, in cross_entropy
    return nll_loss(log_softmax(input, 1), target, weight, None, ignore_index, None, reduction)
  File "/my/venv/lib/python3.8/site-packages/torch/nn/functional.py", line 2384, in nll_loss
    raise ValueError(
ValueError: Expected input batch_size (3328) to match target batch_size (3296).
```

実行している環境は次の通りです
OS: Ubuntu 18.04
Python: 3.8.1
Transformers: 4.9.2
PyTorch: 1.8.2
CUDA: 11.1
CuDNN: 8.1.1

学習に使用しているデータは以下のページにある「2020jp_tokenize_mecab_ipadic_bpe_tohoku_bert」のデータセットです。
http://shinra-project.info/shinra2020jp/data_download/?tax%5Bwpdmcategory%5D=2020jp-dist-data-tokenize

上記エラーの発生原因は分かりますでしょうか？

**Comment by ujiuji1259** [comment]
ご報告ありがとうございます．
こちらでエラーが再現しまして，[こちらのコミット](https://github.com/ujiuji1259/shinra-attribute-extraction/commit/ee302e2b4bf01debf568beb7b2778bf7f7494398)で単語オフセット`word_indx`の末尾に文長を加えていたところを，`create_pooler_matrix()`に反映していないのが原因のようでした．
[この修正](https://github.com/ujiuji1259/shinra-attribute-extraction/commit/f588af042e611d2f7345078008b0351e81c808fc)でこちらの環境では動作を確認しましたがいかがでしょうか．

**Comment by ymym3412** [comment]
ありがとうございます。
mainブランチのコードで上記のissueが解決されたことを確認しました。
本件closeします。
